services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword      
      MYSQL_DATABASE: mydatabase             
      MYSQL_USER: appuser                    
      MYSQL_PASSWORD: appuserpassword        
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  auth:
    build: ./auth
    ports:
      - "8001:8001"
    environment:
      - DB_USER=appuser
      - DB_PASS=appuserpassword
      - DB_NAME=mydatabase
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - app-network

  todo:
    build: ./todo
    ports:
      - "8002:8002"
    environment:
      - DB_USER=appuser
      - DB_PASS=appuserpassword
      - DB_NAME=mydatabase
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - app-network

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth
      - todo
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
