
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  auth:
    build: ./auth
    ports:
      - "50051:50051"  
    environment:
      - DB_USER=appuser
      - DB_PASS=appuserpassword
      - DB_NAME=mydatabase
    depends_on:
      - db
    networks:
      - app-network


volumes:
  db_data:

networks:
  app-network:
    driver: bridge

